<a href="https://colab.research.google.com/github/tusharsharm/MDSC-302/blob/main/24040208008_MDSC_302_DEEP_LEARNING_ASSIGNMENT_IV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 24040208008 MDSC-302 DEEP LEARNING ASSIGNMENT-IV

# Analyze a large Python source code file by:
- a) building a word index using simple tokenization,
-  b) comparing its size to an index of "Pride and Prejudice",
-  c) creating a one-hot encoding,
-  d) discussing the information lost in the encoding compared to the "Pride and Prejudice" encoding.

## Select a python source code file


## Tokenize the source code

### Subtask:
Implement a tokenization process for the selected source code file.


**Reasoning**:
Read the content of the specified Python file, define a tokenization function, and apply it to the file content to get a list of tokens.



In [10]:
import re
from collections import defaultdict
file_path = "/content/large_python_file.py"
with open(file_path, "r") as f:
    file_content = f.read()

def simple_tokenize(text):
    # Convert to lower case
    text = text.lower()
    # Remove punctuation and split into words
    tokens = re.sub(r"[^a-zA-Z0-9_]+", " ", text).split()
    return tokens

tokens = simple_tokenize(file_content)
index = defaultdict(list)
for pos, token in enumerate(tokens):
    index[token].append(pos)

# Print stats
print(f"Unique words in file: {len(index)}")
print(f"Total tokens: {len(tokens)}")
print(f"First 10 tokens: {tokens[:10]}")

Unique words in file: 96
Total tokens: 267
First 10 tokens: ['import', 'os', 'import', 'sys', 'import', 'time', 'def', 'factorial', 'n', 'if']


## Compare indices


Compare the size of the index from the source code with an index created for "Pride and Prejudice".


In [13]:
file_path = "/content/1342-0.txt"
with open(file_path, "r") as f:
    file_content = f.read()

pride_count = len(simple_tokenize(file_content))
code_count = len(index)

if code_count > pride_count:
    print(f"Python code has more unique tokens.{code_count} > {pride_count}")
else:
    print(f"Pride and Prejudice has more unique tokens.{pride_count} > {code_count}")


Pride and Prejudice has more unique tokens.126078 > 96


## Create one-hot encoding

Generate the one-hot encoding for the source code file based on the created index.


In [16]:
import numpy as np

# Map each token to an index
word_to_idx = {word: i for i, word in enumerate(index.keys())}

# Create one-hot vectors for each token in order
vocab_size = len(word_to_idx)
one_hot_matrix = np.zeros((len(tokens), vocab_size), dtype=int)
print(one_hot_matrix,"\n")
for i, token in enumerate(tokens):
    one_hot_matrix[i, word_to_idx[token]] = 1

print(one_hot_matrix.shape)  # (num_tokens, vocab_size)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 

(267, 96)
